@url = http://localhost:5000

POST {{url}}/api/recommendations/anonymous
Content-Type: application/json

{
  "gender": "Male",
  "bodyType": "Athletic",
  "ageRange": "25-30",
  "occasion": "Evening party",
  "season": "Winter",
  "temperature": "Cold",
  "additionalPreferences": "Classic, elegant, dark colors"
}

###